env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/react

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

settings:
  react:
    version: detect
