name: Test

on:
  - pull_request
  - push

env:
  CACHE_PREFIX: v1
  YARN_VERSION: '^1.22.4'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || !startsWith(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v2

      - name: Detect Node version from .nvmrc
        id: node_version
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.node_version.outputs.nvmrc }}

      - name: Install yarn
        id: yarn
        run: |
          cd $HOME && yarn policies set-version $YARN_VERSION
          echo "::set-output name=cache_dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn.outputs.cache_dir }}
          key: yarn_cache-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn_cache-${{ env.CACHE_PREFIX }}-

      - run: yarn install
      - run: yarn audit

      - name: Prettier formatting
        run: yarn check:format

      - name: ESLint
        run: yarn lint:js

      - name: TypeScript type checking
        run: yarn check:ts
